name: Markdown to PDF and HTML Conversion

permissions:
  contents: write  

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Convert Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: ./README.md
          output_dir: ./pdf
          build_pdf: true
          build_html: false
          table_of_contents: false
          
      - name: Commit generated PDF to repository
        run: |
          git pull origin main
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          mv pdfREADME.pdf ./pdf/ || true
          git add ./pdf/*
          git commit -m "Add generated PDFs" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/umbertocicciaa/Theoretical-Computer-Science.git
          
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Theoretical-Computer-Science
          path: ./pdf
